name: itrue-iperf3
base: core22
version: git
summary: A TCP, UDP, and SCTP network bandwidth measurement tool
description: |
  iperf is a tool for active measurements of the maximum achievable bandwidth on
  IP networks. It supports tuning of various parameters related to timing,
  protocols, and buffers. For each test it reports the measured
  throughput/bitrate, loss, and other parameters.

  **Note: This is an unoffical snap not developed or managed by the iperf
  developers!**

grade: stable
confinement: strict

parts:
  iperf3:
    plugin: nil
    stage-packages:
      - iperf3
    prime:
      - -usr/share

apps:
  itrue-iperf3:
    command: usr/bin/iperf3
    plugs:
      - network
      - network-control
